<?php
$kon = array();
array_push(
    $kon,
    $_POST['nisn'],
    $_POST['asl_sklh'],
    $_POST['th_lulus'],
    $_POST['file_ijazah'],
    $_POST['nama'],
    $_POST['nik'],
    $_POST['tmpt_lhr'],
    $_POST['tgl_lhr'],
    $_POST['umur'],
    $_POST['file_akta'],
    $_POST['jenis_kelamin'],
    $_POST['alamat'],
    $_POST['desa'],
    $_POST['kecamatan'],
    $_POST['kabupaten'],
    $_POST['provinsi'],
    $_POST['email'],
    $_POST['file_kk'],
    $_POST['no_kk'],
    $_POST['nama_ayah'],
    $_POST['agama_ayah'],
    $_POST['kerja_ayah'],
    $_POST['nama_ibu'],
    $_POST['agama_ibu'],
    $_POST['kerja_ibu'],
    $_POST['alamat_ortu'],
    $_POST['desa_ortu'],
    $_POST['kecamatan_ortu'],
    $_POST['kabupaten_ortu'],
    $_POST['provinsi_ortu']
);

var_dump($kon);